---
sudo: false
language: ruby
rvm:
  - 2.4
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script: bundle install && bundle exec rspec && cd ./test_app && bundle install && bundle exec rspec
